# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4141678cda40f7a88d61eae3e3cf3175a6cac48c205440e9e0a944c4c5d50f1f4d25d6068970a2defa2da3b56da75d6e9561d07eab964497a783afdf94805dd

test:
  secret_key_base: e274bc110882cdce063c1ddfbaa6d3215fb963aa29052bea2aa112037d0a7441b45a3062460c07da5211bab87373f0031124adbc3bf39ae60681ebc77fabeb4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
